CREATE TABLE hashtag
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    CHECK cons_hashtag_name_length (LENGTH(name) <= 30),
    PRIMARY KEY pkey_hashtag (id)
);
CREATE INDEX idx_hashtag_name ON hashtag (name);

CREATE TABLE image
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    submit_date TIMESTAMP,
    description TEXT CHECK cons_image_description_length (LENGTH(description) <= 500),
    image       BLOB,
    name        TEXT NOT NULL CHECK cons_image_name_length (LENGTH(name) <= 100),
    PRIMARY KEY pkey_image (id)
);

CREATE TABLE images_hashtags
(
    image_id   BIGINT NOT NULL,
    hashtag_id BIGINT NOT NULL,
    PRIMARY KEY pkey_images_hashtags (image_id, hashtag_id),
    FOREIGN KEY fkey_images_hashtags_image_id (image_id) REFERENCES image(id),
    FOREIGN KEY fkey_images_hashtags_hashtag_id (hashtag_id) REFERENCES hashtag(id)
);

CREATE INDEX idx_images_hashtags_image_id ON images_hashtags (image_id);
CREATE INDEX idx_images_hashtags_hashtag_id ON images_hashtags (hashtag_id);
