CREATE TABLE hashtag
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    CONSTRAINT cons_hashtag_name_length CHECK  (LENGTH(name) <= 30),
    CONSTRAINT pkey_hashtag PRIMARY KEY  (id)
);
CREATE INDEX idx_hashtag_name ON hashtag (name);

CREATE TABLE image
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    submit_date TIMESTAMPTZ,
    name        TEXT NOT NULL CONSTRAINT cons_image_name_length CHECK  (LENGTH(name) <= 100),
    description TEXT CONSTRAINT cons_image_description_length CHECK  (LENGTH(description) <= 500),
    image       BYTEA,

    CONSTRAINT pkey_image PRIMARY KEY  (id)
);

CREATE TABLE images_hashtags
(
    image_id   BIGINT NOT NULL,
    hashtag_id BIGINT NOT NULL,
    CONSTRAINT pkey_images_hashtags PRIMARY KEY  (image_id, hashtag_id),
    CONSTRAINT fkey_images_hashtags_image_id FOREIGN KEY  (image_id) REFERENCES image(id),
    CONSTRAINT fkey_images_hashtags_hashtag_id FOREIGN KEY (hashtag_id) REFERENCES hashtag(id)
);

CREATE INDEX idx_images_hashtags_image_id ON images_hashtags (image_id);
CREATE INDEX idx_images_hashtags_hashtag_id ON images_hashtags (hashtag_id);
